services:
  app-drf-authentication:
    build:
      context: ../../FastAPI-Authentication/
      dockerfile: Dockerfile
    container_name: app-drf-authentication
    ports:
      - "8000:8000"
    expose:
      - 8000
    env_file:
      - ../.env
    depends_on:
      - postgres
    command: ["poetry", "run", "python", "-Om", "src.main:main"]
    networks:
      - ppostgres.network

networks:
  ppostgres.network:
    driver: bridge
