services:
  postgres_backup:
    container_name: ppostgres_backup
    image: prodrigestivill/postgres-backup-local:15-alpine
    networks:
      - ppostgres.network
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=${DATABASE_NAME:-${DATABASE_USER:-$USER}}
      - DATABASE_USER=${DATABASE_USER:-$USER}
      - DATABASE_PASSWORD=$DATABASE_PASSWORD
      - BACKUP_DIR=/backups
      - POSTGRES_EXTRA_OPTS=-Z6 --schema=public --blobs
      - SCHEDULE=${POSTGRES_BACKUP_SCHEDULE:-@daily}
      - HEALTHCHECK_PORT=8080
    volumes:
      - ${POSTGRES_BACKUP_DIR:-./backups}:/backups

networks:
  ppostgres.network: {}
