services:
  postgres:
    container_name: ppostgres
    image: "postgres:15-alpine"
    restart: unless-stopped
    expose:
      - "5432"
    ports:
      - "5432:5432"
    environment:
      DATABASE_PASSWORD: $DATABASE_PASSWORD
      DATABASE_USER: ${DATABASE_USER:-$USER}
      DATABASE_NAME: ${DATABASE_NAME:-${DATABASE_USER:-$USER}}
    networks:
      - ppostgres.network
    volumes:
      - "ppostgres.data:/var/lib/postgresql/data:rw"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${DATABASE_NAME} -U $${DATABASE_USER}"]
      interval: 10s
      timeout: 60s
      retries: 5
      start_period: 10s
    env_file:
      - ../.env

volumes:
  ppostgres.data: {}

networks:
  ppostgres.network: {}
